/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "ForexHacked 2.1"
#property link      "http://www.ForexHacked.com"


extern string User = "Your ForexHacked.com Username";
extern string _________ = "Magic Number Must be UNIQUE for each chart!";
extern int MagicNumber = 133714;
extern double Lots = 0.01;
extern double TakeProfit = 132.0;
extern double Booster = 2.0;
extern int PipStarter = 170;
double gd_124 = 0.0;
int gi_132 = 0;
int gi_136 = 0;
extern int MaxBuyOrders = 9;
extern int MaxSellOrders = 9;
extern bool AllowiStopLoss = FALSE;
extern int iStopLoss = 300;
extern int StartHour = 0;
extern int StartMinute = 0;
extern int StopHour = 23;
extern int StopMinute = 55;
extern int StartingTradeDay = 0;
extern int EndingTradeDay = 7;
extern int slippage = 3;
int gi_184 = 5000;
int gi_188 = 0;
int gi_192 = 0;
extern double StopLossPct = 100.0;
extern double TakeProfitPct = 25.0;
extern bool PauseNewTrades = FALSE;
extern int StoppedOutPause = 600;
double gd_220;
bool gi_236;
int g_period_240 = 7;
int gi_244 = 0;
int g_ma_method_248 = MODE_LWMA;
int g_applied_price_252 = PRICE_WEIGHTED;
double gd_256 = 0.25;
double gd_264 = 0.2;
extern bool SupportECN = TRUE;
extern bool MassHedge = FALSE;
extern double MassHedgeBooster = 1.01;
extern int TradesDeep = 4;
extern string EA_Name = "Forex Hacked 2.1";
int g_datetime_300;
int gi_304;
bool gi_unused_308 = FALSE;
string gs_dummy_312;
int gi_320;
int gi_324;
int gi_328 = 0;
int gi_332 = 1;
int gi_unused_336 = 3;
int gi_340 = 250;
string gs_344;
bool gi_352;
bool gi_356;
bool gi_360;
bool gi_364;
int g_ticket_368;
int g_cmd_372;
string gs__hedged_376 = " hedged";
int g_file_384;

void Log(string as_0) {
   if (g_file_384 >= 0) FileWrite(g_file_384, TimeToStr(TimeCurrent(), TIME_DATE|TIME_SECONDS) + ": " + as_0);
}

int GetLotDigits() {
   double ld_4 = MarketInfo(Symbol(), MODE_MINLOT);
   for (int l_count_0 = 0; ld_4 < 1.0; l_count_0++) ld_4 = 10.0 * ld_4;
   return (l_count_0);
}

double CalcLots(double ad_0) {
   double l_minlot_32;
   double ld_8 = AccountEquity() - gi_184;
   double ld_16 = gi_188;
   double ld_24 = gi_192;
   if (gi_188 == 0 || gi_192 == 0) l_minlot_32 = ad_0;
   else {
      ld_16 = gi_184 * ld_16 / 100.0;
      Print("tmp=" + ld_8 + ",AccountEquity()=" + AccountEquity() + ",InitEquity=" + gi_184);
      ld_24 /= 100.0;
      if (ld_8 > 0.0) ld_8 = MathPow(ld_24 + 1.0, ld_8 / ld_16);
      else {
         if (ld_8 < 0.0) ld_8 = MathPow(1 - ld_24, MathAbs(ld_8 / ld_16));
         else ld_8 = 1;
      }
      l_minlot_32 = NormalizeDouble(ad_0 * ld_8, GetLotDigits());
      if (l_minlot_32 < MarketInfo(Symbol(), MODE_MINLOT)) l_minlot_32 = MarketInfo(Symbol(), MODE_MINLOT);
   }
   if (l_minlot_32 < 0.0) Print("ERROR tmp=" + ld_8 + ",a=" + ld_16 + ",b=" + ld_24 + ",AccountEquity()=" + AccountEquity());
   return (l_minlot_32);
}


int deinit() {
   FileClose(g_file_384);
   return (0);
}

int init() {
   if (Digits == 3) {
      gd_124 = 10.0 * TakeProfit;
      gi_132 = 10.0 * PipStarter;
      gi_136 = 10.0 * iStopLoss;
   } else {
      if (Digits == 5) {
         gd_124 = 10.0 * TakeProfit;
         gi_132 = 10.0 * PipStarter;
         gi_136 = 10.0 * iStopLoss;
      } else {
         gd_124 = TakeProfit;
         gi_132 = PipStarter;
         gi_136 = iStopLoss;
      }
   }
   gi_304 = MathRound((-MathLog(MarketInfo(Symbol(), MODE_LOTSTEP))) / 2.302585093);
   gi_352 = FALSE;
   gi_356 = FALSE;
   gi_360 = FALSE;
   gi_364 = FALSE;
   g_ticket_368 = -1;
   gi_236 = FALSE;
   g_file_384 = FileOpen(WindowExpertName() + "_" + Time[0] + "_" + Symbol() + "_" + MagicNumber + ".log", FILE_WRITE);
   g_cmd_372 = -1;
   if (IsDemo() == TRUE) gs_344 = "approved";
   return (0);
}

int IsTradeTime() {
   int li_8;
   int li_0 = 60 * TimeHour(TimeCurrent()) + TimeMinute(TimeCurrent());
   int li_4 = 60 * StartHour + StartMinute;
   li_8 = 60 * StopHour + li_8;
   if (li_4 == li_8) return (1);
   if (li_4 < li_8) {
      if (!(li_0 >= li_4 && li_0 < li_8)) return (0);
      return (1);
   }
   if (li_4 > li_8) {
      if (!(li_0 >= li_4 || li_0 < li_8)) return (0);
      return (1);
   }
   return (0);
}

double GetLastLotSize(int ai_0) {
   for (int l_pos_4 = OrdersTotal() - 1; l_pos_4 >= 0; l_pos_4--) {
      if (OrderSelect(l_pos_4, SELECT_BY_POS)) {
         if (OrderMagicNumber() == MagicNumber) {
            if (StringFind(OrderComment(), gs__hedged_376) == -1) {
               Log("GetLastLotSize " + ai_0 + ",OrderLots()=" + OrderLots());
               return (OrderLots());
            }
         }
      }
   }
   Log("GetLastLotSize " + ai_0 + " wasnt found");
   return (0);
}

bool OpenBuy(bool ai_0 = FALSE) {
   int l_ticket_4;
   double l_lots_40;
   double l_price_8 = 0;
   double l_price_16 = 0;
   string ls_24 = "";
   bool li_ret_32 = TRUE;
   if (TimeCurrent() - g_datetime_300 < 60 * Period()) return (FALSE);
   if (ai_0 && !gi_360) return (FALSE);
   if (!GlobalVariableCheck("PERMISSION")) {
      GlobalVariableSet("PERMISSION", TimeCurrent());
      if (!SupportECN) {
         if (ai_0) {
            if (OrderSelect(g_ticket_368, SELECT_BY_TICKET)) l_price_16 = OrderTakeProfit() - MarketInfo(Symbol(), MODE_SPREAD) * Point;
         } else l_price_8 = Ask + gd_124 * Point;
      }
      if (ai_0) ls_24 = gs__hedged_376;
      if (IsTradeTime() == 1 && DayOfWeek() >= StartingTradeDay && DayOfWeek() <= EndingTradeDay) {
         if (AllowiStopLoss == TRUE) l_price_16 = Ask - gi_136 * Point;
         if (ai_0) l_lots_40 = NormalizeDouble(GetLastLotSize(1) * MassHedgeBooster, 2);
         else l_lots_40 = CalcLots(gd_220);
         l_ticket_4 = OrderSend(Symbol(), OP_BUY, l_lots_40, Ask, slippage, l_price_16, l_price_8, EA_Name + ls_24, MagicNumber, 0, Green);
         g_datetime_300 = TimeCurrent();
      }
      if (l_ticket_4 != -1) {
         if (!ai_0) {
            g_ticket_368 = l_ticket_4;
            Log("BUY hedgedTicket=" + g_ticket_368);
         } else {
            Log("BUY Hacked_ticket=" + l_ticket_4);
            g_cmd_372 = 0;
         }
      } else {
         Log("failed sell");
         li_ret_32 = FALSE;
      }
   }
   GlobalVariableDel("PERMISSION");
   return (li_ret_32);
}

bool OpenSell(bool ai_0 = FALSE) {
   int l_ticket_4;
   double l_lots_36;
   double l_price_8 = 0;
   double l_price_16 = 0;
   string ls_24 = "";
   bool li_ret_32 = TRUE;
   if (TimeCurrent() - g_datetime_300 < 60 * Period()) return (FALSE);
   if (ai_0 && !gi_364) return (FALSE);
   if (!GlobalVariableCheck("PERMISSION")) {
      GlobalVariableSet("PERMISSION", TimeCurrent());
      if (!SupportECN) {
         if (ai_0) {
            if (OrderSelect(g_ticket_368, SELECT_BY_TICKET)) l_price_16 = OrderTakeProfit() + MarketInfo(Symbol(), MODE_SPREAD) * Point;
         } else l_price_8 = Bid - gd_124 * Point;
      }
      if (ai_0) ls_24 = gs__hedged_376;
      if (IsTradeTime() == 1 && DayOfWeek() >= StartingTradeDay && DayOfWeek() <= EndingTradeDay) {
         if (AllowiStopLoss == TRUE) l_price_16 = Bid + gi_136 * Point;
         if (ai_0) l_lots_36 = NormalizeDouble(GetLastLotSize(0) * MassHedgeBooster, 2);
         else l_lots_36 = CalcLots(gd_220);
         l_ticket_4 = OrderSend(Symbol(), OP_SELL, l_lots_36, Bid, slippage, l_price_16, l_price_8, EA_Name + ls_24, MagicNumber, 0, Pink);
         g_datetime_300 = TimeCurrent();
      }
      if (l_ticket_4 != -1) {
         if (!ai_0) {
            g_ticket_368 = l_ticket_4;
            Log("SELL hedgedTicket=" + g_ticket_368);
         } else {
            Log("SELL Hacked_ticket=" + l_ticket_4);
            g_cmd_372 = 1;
         }
      } else {
         Log("failed sell");
         li_ret_32 = FALSE;
      }
   }
   GlobalVariableDel("PERMISSION");
   return (li_ret_32);
}

void ManageBuy() {
   int l_datetime_0 = 0;
   double l_ord_open_price_4 = 0;
   double l_ord_lots_12 = 0;
   double l_ord_takeprofit_20 = 0;
   int l_cmd_28 = -1;
   int l_ticket_32 = 0;
   int l_pos_36 = 0;
   for (l_pos_36 = 0; l_pos_36 < OrdersTotal(); l_pos_36++) {
      if (OrderSelect(l_pos_36, SELECT_BY_POS, MODE_TRADES)) {
         if (OrderMagicNumber() == MagicNumber && OrderType() == OP_BUY) {
            if (OrderOpenTime() > l_datetime_0 && IsTradeTime() == 1) {
               l_datetime_0 = OrderOpenTime();
               l_ord_open_price_4 = OrderOpenPrice();
               l_cmd_28 = OrderType();
               l_ticket_32 = OrderTicket();
               l_ord_takeprofit_20 = OrderTakeProfit();
            }
            if (OrderLots() > l_ord_lots_12) l_ord_lots_12 = OrderLots();
         }
      }
   }
   double l_isar_40 = iSAR(NULL, 0, gd_256, gd_264, 0);
   double l_ima_48 = iMA(NULL, 0, g_period_240, gi_244, g_ma_method_248, g_applied_price_252, 0);
   int li_56 = MathRound(MathLog(l_ord_lots_12 / Lots) / MathLog(Booster)) + 1.0;
   if (li_56 < 0) li_56 = 0;
   gd_220 = NormalizeDouble(Lots * MathPow(Booster, li_56), gi_304);
   if (li_56 == 0 && l_isar_40 < l_ima_48) {
      if (DayOfWeek() < EndingTradeDay || (DayOfWeek() >= StartingTradeDay && DayOfWeek() <= EndingTradeDay)) {
         if (OpenBuy())
            if (MassHedge) gi_352 = TRUE;
      }
   }
   if (l_ord_open_price_4 - Ask > gi_132 * Point && li_56 < MaxSellOrders) {
      if (!(OpenBuy())) return;
      if (!(MassHedge)) return;
      gi_352 = TRUE;
      return;
   }
   for (l_pos_36 = 0; l_pos_36 < OrdersTotal(); l_pos_36++) {
      OrderSelect(l_pos_36, SELECT_BY_POS, MODE_TRADES);
      if (OrderMagicNumber() != MagicNumber || OrderType() != OP_BUY || OrderTakeProfit() == l_ord_takeprofit_20 || l_ord_takeprofit_20 == 0.0) continue;
      OrderModify(OrderTicket(), OrderOpenPrice(), OrderStopLoss(), l_ord_takeprofit_20, 0, Pink);
   }
}

void ManageSell() {
   int l_datetime_0 = 0;
   double l_ord_open_price_4 = 0;
   double l_ord_lots_12 = 0;
   double l_ord_takeprofit_20 = 0;
   int l_cmd_28 = -1;
   int l_ticket_32 = 0;
   int l_pos_36 = 0;
   for (l_pos_36 = 0; l_pos_36 < OrdersTotal(); l_pos_36++) {
      if (OrderSelect(l_pos_36, SELECT_BY_POS, MODE_TRADES)) {
         if (OrderMagicNumber() == MagicNumber && OrderType() == OP_SELL) {
            if (OrderOpenTime() > l_datetime_0 && IsTradeTime() == 1) {
               l_datetime_0 = OrderOpenTime();
               l_ord_open_price_4 = OrderOpenPrice();
               l_cmd_28 = OrderType();
               l_ticket_32 = OrderTicket();
               l_ord_takeprofit_20 = OrderTakeProfit();
            }
            if (OrderLots() > l_ord_lots_12) l_ord_lots_12 = OrderLots();
         }
      }
   }
   double l_isar_40 = iSAR(NULL, 0, gd_256, gd_264, 0);
   double l_ima_48 = iMA(NULL, 0, g_period_240, gi_244, g_ma_method_248, g_applied_price_252, 0);
   int li_56 = MathRound(MathLog(l_ord_lots_12 / Lots) / MathLog(Booster)) + 1.0;
   if (li_56 < 0) li_56 = 0;
   gd_220 = NormalizeDouble(Lots * MathPow(Booster, li_56), gi_304);
   if (li_56 == 0 && l_isar_40 > l_ima_48) {
      if (DayOfWeek() < EndingTradeDay || (DayOfWeek() >= StartingTradeDay && DayOfWeek() <= EndingTradeDay)) {
         if (OpenSell())
            if (MassHedge) gi_356 = TRUE;
      }
   }
   if (Bid - l_ord_open_price_4 > gi_132 * Point && l_ord_open_price_4 > 0.0 && li_56 < MaxSellOrders) {
      if (!(OpenSell())) return;
      if (!(MassHedge)) return;
      gi_356 = TRUE;
      return;
   }
   for (l_pos_36 = 0; l_pos_36 < OrdersTotal(); l_pos_36++) {
      if (OrderSelect(l_pos_36, SELECT_BY_POS, MODE_TRADES)) {
         if (OrderMagicNumber() == MagicNumber && OrderType() == OP_SELL) {
            if (OrderTakeProfit() == l_ord_takeprofit_20 || l_ord_takeprofit_20 == 0.0) continue;
            OrderModify(OrderTicket(), OrderOpenPrice(), OrderStopLoss(), l_ord_takeprofit_20, 0, Pink);
         }
      }
   }
}

int start() {
   double l_ord_takeprofit_20;
   double l_price_28;
   double l_price_36;
   int l_count_4 = 0;
   int l_count_8 = 0;
   for (int l_pos_12 = 0; l_pos_12 < OrdersTotal(); l_pos_12++) {
      if (OrderSelect(l_pos_12, SELECT_BY_POS, MODE_TRADES)) {
         if (OrderMagicNumber() == MagicNumber) {
            if (StringFind(OrderComment(), gs__hedged_376) == -1) {
               if (OrderType() == OP_BUY) l_count_4++;
               else
                  if (OrderType() == OP_SELL) l_count_8++;
            }
         }
      }
   }
   if (l_count_4 >= TradesDeep) {
      if (!gi_364) {
         Log("Allow long hedge! trades=" + l_count_4 + ",TradesDeep=" + TradesDeep);
         gi_364 = TRUE;
      }
   }
   if (l_count_8 >= TradesDeep) {
      if (!gi_360) {
         Log("Allow short hedge! trades=" + l_count_8 + ",TradesDeep=" + TradesDeep);
         gi_360 = TRUE;
      }
   }
   bool li_16 = FALSE;
   if ((100 - StopLossPct) * AccountBalance() / 100.0 >= AccountEquity()) {
      Log("AccountBalance=" + AccountBalance() + ",AccountEquity=" + AccountEquity());
      gi_236 = TRUE;
      li_16 = TRUE;
   }
   if ((TakeProfitPct + 100.0) * AccountBalance() / 100.0 <= AccountEquity()) gi_236 = TRUE;
   if (gi_236) {
      for (int l_pos_0 = OrdersTotal() - 1; l_pos_0 >= 0; l_pos_0--) {
         if (OrderSelect(l_pos_0, SELECT_BY_POS)) {
            if (OrderMagicNumber() == MagicNumber) {
               Log("close #" + OrderTicket());
               if (!OrderClose(OrderTicket(), OrderLots(), OrderClosePrice(), MarketInfo(Symbol(), MODE_SPREAD), White)) {
                  Log("error");
                  return (0);
               }
            }
         }
      }
      gi_236 = FALSE;
      if (li_16) {
         Sleep(1000 * StoppedOutPause);
         li_16 = FALSE;
      }
      gi_364 = FALSE;
      gi_360 = FALSE;
   }
   if (SupportECN) {
      l_ord_takeprofit_20 = 0;
      if (OrderSelect(g_ticket_368, SELECT_BY_TICKET)) l_ord_takeprofit_20 = OrderTakeProfit();
      for (l_pos_0 = 0; l_pos_0 < OrdersTotal(); l_pos_0++) {
         if (OrderSelect(l_pos_0, SELECT_BY_POS)) {
            if (OrderMagicNumber() == MagicNumber) {
               if (OrderTakeProfit() == 0.0 && StringFind(OrderComment(), gs__hedged_376) == -1) {
                  if (OrderType() == OP_BUY) OrderModify(OrderTicket(), 0, OrderStopLoss(), OrderOpenPrice() + gd_124 * Point, 0, White);
                  else
                     if (OrderType() == OP_SELL) OrderModify(OrderTicket(), 0, OrderStopLoss(), OrderOpenPrice() - gd_124 * Point, 0, White);
               } else {
                  if (StringFind(OrderComment(), gs__hedged_376) != -1 && g_cmd_372 == OrderType()) {
                     l_price_28 = l_ord_takeprofit_20 - MarketInfo(Symbol(), MODE_SPREAD) * Point;
                     l_price_36 = l_ord_takeprofit_20 + MarketInfo(Symbol(), MODE_SPREAD) * Point;
                     if (OrderStopLoss() == 0.0 || (OrderType() == OP_BUY && OrderStopLoss() != l_price_28) || (OrderType() == OP_SELL && OrderStopLoss() != l_price_36)) {
                        if (OrderType() == OP_BUY) OrderModify(OrderTicket(), 0, l_price_28, OrderTakeProfit(), 0, White);
                        else
                           if (OrderType() == OP_SELL) OrderModify(OrderTicket(), 0, l_price_36, OrderTakeProfit(), 0, White);
                     }
                  }
               }
            }
         }
      }
   }
   if (Check() != 0) {
      ManageBuy();
      ManageSell();
      if (!PauseNewTrades) {
         if (gi_356)
            if (OpenBuy(1)) gi_356 = FALSE;
         if (gi_352)
            if (OpenSell(1)) gi_352 = FALSE;
      }
      ChartComment();
      return (0);
   }
   return (0);
}

void ChartComment() {
   string l_dbl2str_0 = DoubleToStr(balanceDeviation(2), 2);
   Comment(" \nForexHacked V2.1™ ", 
      "\nAccount Leverage  :  " + "1 : " + AccountLeverage(), 
      "\nAccount Type  :  " + AccountServer(), 
      "\nServer Time  :  " + TimeToStr(TimeCurrent(), TIME_SECONDS), 
      "\nAccount Equity  = ", AccountEquity(), 
      "\nFree Margin     = ", AccountFreeMargin(), 
   "\nDrawdown  :  ", l_dbl2str_0, "%\n");
}

int Check() {
   return (1);
}

double balanceDeviation(int ai_0) {
   double ld_ret_4;
   if (ai_0 == 2) {
      ld_ret_4 = (AccountEquity() / AccountBalance() - 1.0) / (-0.01);
      if (ld_ret_4 > 0.0) return (ld_ret_4);
      return (0);
   }
   if (ai_0 == 1) {
      ld_ret_4 = 100.0 * (AccountEquity() / AccountBalance() - 1.0);
      if (ld_ret_4 > 0.0) return (ld_ret_4);
      return (0);
   }
   return (0.0);
}